@startuml
|Пользователь|
start
:Открывает сайт;
:Просматривает каталог;
if (Выбор товара?) then (да)
  :Добавляет в корзину;
endif
:Переходит в корзину;
if (Готов оформить заказ?) then (да)
  :Авторизация/Регистрация;
  :Оформляет заказ;
  |Backend|
  :Сохранение заказа в БД;
  :Отправка сообщения в Kafka;
  |Kafka|
  :Публикация события "Новый заказ";
  |Backend|
  :Обновление остатков товара;
  :Обновление статуса заказа в БД;
else (нет)
  :Возвращается в каталог;
endif
stop

@enduml